/*
 * This file was automatically generated by EvoSuite
 * Thu Nov 22 13:12:14 BRT 2018
 */

package whenDoc.whenDOc.entity;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import whenDoc.whenDOc.entity.Alergia;
import whenDoc.whenDOc.entity.Paciente;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true) 
public class Alergia_ESTest extends Alergia_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Alergia alergia0 = new Alergia();
      alergia0.setNome_Alergia("y");
      String string0 = alergia0.getNome_Alergia();
      assertEquals("y", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Alergia alergia0 = new Alergia();
      String string0 = alergia0.getNome_Alergia();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Alergia alergia0 = new Alergia();
      Long long0 = new Long(0L);
      Paciente paciente0 = new Paciente("", long0, "", "", "", "", "", "", false);
      alergia0.setPaciente(paciente0);
      assertEquals("", paciente0.getEmailSec());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Alergia alergia0 = new Alergia();
      alergia0.setNome_Alergia("");
      String string0 = alergia0.getNome_Alergia();
      assertEquals("", string0);
  }
}
