/*
 * This file was automatically generated by EvoSuite
 * Tue Nov 13 19:50:57 BRT 2018
 */

package whenDoc.whenDOc.service;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true) 
public class AlergiasService_ESTest extends AlergiasService_ESTest_scaffolding {
  @Test
  public void notGeneratedAnyTest() {
    // EvoSuite did not generate any tests
  }
}
