/*
 * This file was automatically generated by EvoSuite
 * Tue Nov 13 19:51:48 BRT 2018
 */

package whenDoc.whenDOc.controller;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true) 
public class PacientController_ESTest extends PacientController_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PacientController pacientController0 = new PacientController();
  }
}
